-- employees 에서 전체 내용 조회
SELECT * 
FROM EMPLOYEES e ;

-- first_name, last_name, job_id 조회
SELECT first_name, last_name, job_id
FROM EMPLOYEES e ;

-- 사원번호가 176인 사람의 LAST_NAME 과 DEPARTMENT_ID 조회
SELECT LAST_NAME , DEPARTMENT_ID 
FROM EMPLOYEES e
WHERE EMPLOYEES ID = 176;

-- 연봉이 12000 이상 되는 직원들의 LAST_NAME 과 SALARY 조회
SELECT LAST_NAME , SALARY 
FROM EMPLOYEES e 
WHERE SALARY >=12000;

-- 연봉이 5000 에서 12000 의 번위 이외인 사람들의 LAST_NAME 과 SALARY 조회
SELECT LAST_NAME , SALARY 
FROM EMPLOYEES e 
WHERE SALARY < 5000 OR SALARY > 12000;

SELECT LAST_NAME , SALARY 
FROM EMPLOYEES e 
WHERE SALARY NOT BETWEEN 5000 and 12000;

-- 부서번호가 20, 50 부서에서 근무하는 사람들의 LAST_NAME, DEPARTMENT_ID 조회
SELECT LAST_NAME , DEPARTMENT_ID
FROM EMPLOYEES e 
WHERE DEPARTMENT_ID = 20 OR DEPARTMENT_ID = 50 ;

SELECT LAST_NAME , DEPARTMENT_ID
FROM EMPLOYEES e 
WHERE DEPARTMENT_ID IN (20, 50) ;

-- LAST_NAME, DEPARTMENT_ID 오름차순
SELECT LAST_NAME , DEPARTMENT_ID
FROM EMPLOYEES e 
WHERE DEPARTMENT_ID IN (20, 50) ORDER BY LAST_NAME ASC, DEPARTMENT_ID ASC ;

-- 커미션을 버는 모든 사원들의 LAST_NAME, SALARY, COMMISSION_PCT 조회
SELECT  LAST_NAME , SALARY , COMMISSION_PCT 
FROM EMPLOYEES e 
WHERE COMMISSION_PCT > 0 ORDER BY SALARY DESC, COMMISSION_PCT DESC;

-- SALARY 가 2500, 3500, 7000 이 아니며, SA_REP 나 ST_CLERK 사원 조회
SELECT *
FROM EMPLOYEES e 
WHERE SALARY != 2500 AND SALARY != 3500 AND SALARY <> 7000 AND (JOB_ID = 'SA_REP' OR JOB_ID = 'ST_CLERK') ;

SELECT *
FROM EMPLOYEES e 
WHERE SALARY NOT IN (2500, 3500, 7000) AND JOB_ID IN ('SA_REP', 'ST_CLERK') ; 

-- 2017-01-01 ~2017-12-31 사이에 고용된 사원들의 LAST_NAME, EMPLOYEE_ID, HIRE_DATE 조회
-- HIRE_DATE 내림차순 정렬
SELECT  LAST_NAME, EMPLOYEE_ID, HIRE_DATE
FROM  EMPLOYEES e 
WHERE HIRE_DATE >= '2017-01-01' AND HIRE_DATE <= '2017-12-31'
ORDER BY HIRE_DATE DESC;

SELECT  LAST_NAME, EMPLOYEE_ID, HIRE_DATE
FROM  EMPLOYEES e 
WHERE HIRE_DATE BETWEEN  '2017-01-01' AND '2017-12-31'
ORDER BY HIRE_DATE DESC;

-- 부서번호가 20, 50 부서에서 근무하고, 연봉이 5000~12000 사이인 사원들의 LAST_NAME, SALARY 조회
-- SALARY 오름차순

SELECT LAST_NAME, SALARY
FROM EMPLOYEES e 
WHERE DEPARTMENTS_ID IN (20, 50) AND SALARY BETWEEN 5000 AND 12000
ORDER BY SALARY ASC;